Found ulimit of 10240 and failed to automatically increase with error current limit exceeds maximum limit. This can cause fd limit errors like `OSError: [Errno 24] Too many open files`. Consider increasing with ulimit -n
User-specified max_model_len (16384) is greater than the derived max_model_len (max_position_embeddings=8192 or model_max_length=None in model's config.json). This may lead to incorrect model outputs or CUDA errors. Make sure the value is correct and within the model context size.
[2025-05-12 08:58:59] WARNING tokenizer.py:251: Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
[2025-05-12 08:59:04] INFO core.py:58: Initializing a V1 LLM engine (v0.8.5.post1) with config: model='Qwen/Qwen-1_8B', speculative_config=None, tokenizer='Qwen/Qwen-1_8B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=16384, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='auto', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_model_name=Qwen/Qwen-1_8B, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"level":3,"custom_ops":["none"],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"use_inductor":true,"compile_sizes":[],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":512}
[2025-05-12 08:59:04] WARNING utils.py:2522: Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7fc34a04add0>
[2025-05-12 08:59:05] INFO parallel_state.py:1004: rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0
[2025-05-12 08:59:05] INFO cuda.py:221: Using Flash Attention backend on V1 engine.
[2025-05-12 08:59:05] WARNING topk_topp_sampler.py:69: FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
[2025-05-12 08:59:05] INFO gpu_model_runner.py:1329: Starting to load model Qwen/Qwen-1_8B...
[2025-05-12 08:59:05] INFO weight_utils.py:265: Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:00<00:00,  1.46it/s]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:01<00:00,  1.27it/s]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:01<00:00,  1.30it/s]

[2025-05-12 08:59:07] INFO loader.py:458: Loading weights took 1.69 seconds
[2025-05-12 08:59:08] INFO gpu_model_runner.py:1347: Model loading took 3.4595 GiB and 2.648271 seconds
[2025-05-12 08:59:12] INFO backends.py:420: Using cache directory: /home/aimotion_api/.cache/vllm/torch_compile_cache/5780371a58/rank_0_0 for vLLM's torch.compile
[2025-05-12 08:59:12] INFO backends.py:430: Dynamo bytecode transform time: 4.54 s
[2025-05-12 08:59:16] INFO backends.py:118: Directly load the compiled graph(s) for shape None from the cache, took 3.220 s
[2025-05-12 08:59:16] INFO monitor.py:33: torch.compile takes 4.54 s in total
[2025-05-12 08:59:17] INFO kv_cache_utils.py:634: GPU KV cache size: 321,952 tokens
[2025-05-12 08:59:17] INFO kv_cache_utils.py:637: Maximum concurrency for 16,384 tokens per request: 19.65x
[2025-05-12 08:59:31] INFO gpu_model_runner.py:1686: Graph capturing finished in 15 secs, took 0.36 GiB
[2025-05-12 08:59:31] INFO core.py:159: init engine (profile, create kv cache, warmup model) took 23.80 seconds
[2025-05-12 08:59:31] INFO core_client.py:439: Core engine process 0 ready.
[2025-05-12 08:59:32] WARNING config.py:1239: Default sampling parameters have been overridden by the model's Hugging Face generation config recommended from the model creator. If this is not intended, please relaunch vLLM instance with `--generation-config vllm`.
[2025-05-12 08:59:32] INFO serving_chat.py:118: Using default chat sampling params from model: {'top_k': 0, 'top_p': 0.8, 'max_tokens': 512}
[2025-05-12 08:59:32] INFO serving_completion.py:61: Using default completion sampling params from model: {'top_k': 0, 'top_p': 0.8, 'max_tokens': 512}
[2025-05-12 08:59:32] INFO api_server.py:1090: Starting vLLM API server on http://0.0.0.0:8000
[2025-05-12 08:59:32] INFO launcher.py:28: Available routes are:
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /openapi.json, Methods: HEAD, GET
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /docs, Methods: HEAD, GET
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /docs/oauth2-redirect, Methods: HEAD, GET
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /redoc, Methods: HEAD, GET
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /health, Methods: GET
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /load, Methods: GET
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /ping, Methods: GET, POST
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /tokenize, Methods: POST
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /detokenize, Methods: POST
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /v1/models, Methods: GET
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /version, Methods: GET
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /v1/chat/completions, Methods: POST
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /v1/completions, Methods: POST
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /v1/embeddings, Methods: POST
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /pooling, Methods: POST
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /score, Methods: POST
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /v1/score, Methods: POST
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /v1/audio/transcriptions, Methods: POST
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /rerank, Methods: POST
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /v1/rerank, Methods: POST
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /v2/rerank, Methods: POST
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /invocations, Methods: POST
[2025-05-12 08:59:32] INFO launcher.py:36: Route: /metrics, Methods: GET
INFO:     Started server process [2719937]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
slurmstepd-ki-g0002: error: *** JOB 621 ON ki-g0002 CANCELLED AT 2025-05-12T09:12:09 ***
[2025-05-12 09:12:09] INFO launcher.py:79: Shutting down FastAPI HTTP server.
